name: "Checkout, Install and Test"
description: "Faz o checkout do código, instala as dependências e roda os testes"
inputs:
  use_cache:
    description: "Utilizar cache de dependências"
    required: false
    default: "true"
    type: "boolean"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/cache@v4
      if: inputs.use_cache == 'true'
      id: npm-cache
      with:
        path: node_modules
        key: npm-cache-dir-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm install
      shell: bash

    - name: Run tests
      run: npm test
      shell: bash